require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.4
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Max: 20
Metrics/MethodLength:
  Max: 20
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
